### ISSUE TITLE
New object: parklet 

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#11]
(Needs definition and/or reference images)

**Comment by kfarr** [comment]
From Streetmix:
![image](https://user-images.githubusercontent.com/470477/145898258-1a0c006e-87b0-44b3-b83d-df3feb532188.png)

Image from San Francisco:
![image](https://streetmix.net/images/info-bubble-examples/parklets-01.jpg)

Another picture of a parklet:
![safe_image](https://user-images.githubusercontent.com/470477/145898546-066a76a0-6450-437b-a98f-059c2a4d8f30.jpeg)

**Comment by gnansai** [comment]
Added to street-props
https://github.com/gnansai/3dstreet-assets/tree/main/sets/street-props/gltf-exports
![image](https://user-images.githubusercontent.com/25223402/146877008-38d6c3d0-536a-4030-83c7-6e7bd92df272.png)

**Comment by kfarr** [comment]
release to production! https://github.com/3DStreet/3dstreet/pull/126
