### ISSUE TITLE
New object: utilities (telephone pole)

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#12]
; needs definition and/or reference images

**Comment by kfarr** [comment]
Streetmix illustration: 
![image](https://user-images.githubusercontent.com/470477/145899160-1c17406f-3c2d-47fd-897f-0226c265e7a7.png)

Example low poly object that is similar:
https://poly.pizza/m/4Lp7FdQqR6i

**Comment by kfarr** [comment]
Can add to street-props set

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/street-props/gltf-exports
Added to street Props
![image](https://user-images.githubusercontent.com/25223402/146876748-d23e09fb-a611-434e-abf3-2ac75ca3e13d.png)

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/128
