### ISSUE TITLE
New object: add new modern lamp model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#14]
- issue: current model has weird "wrap around" on pole base, and also does not use existing atlas
- add to street-props set

**Comment by gnansai** [comment]
Please share any reference images for modern lamp.

**Comment by kfarr** [comment]
Here's a doc with light pole spec for SF:
https://sfpuc.org/sites/default/files/documents/SL_Poles-complete.pdf

Snapshot:
![image](https://user-images.githubusercontent.com/470477/147398702-b813e608-8e9f-471a-b3d9-d297325c8693.png)

I think we should try for 25 ft shaft length for "A"

**Comment by kfarr** [comment]
@gnansai you can use the street lights from the polygon shops pack that we have licensed for this project
![image](https://user-images.githubusercontent.com/470477/147724610-e40f7153-12b8-4583-9a84-1ac7164246a6.png)

**Comment by gnansai** [comment]
sure, I will look for that model. I will update you by tonight.

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/147726858-cfe17fbe-476f-4334-acb3-78213b698cba.png)
added street-lamps

**Comment by kfarr** [comment]
looks ok from this view but similar to the utility pole it's hard to tell scale until we see it in context. can add to street-props and then we can put in the queue to test

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/147799122-93acfed2-8621-41bc-8fb9-676adc56ca78.png)
the height of the street lamp when compared to utility pole

**Comment by kfarr** [comment]
The street lamp should be about the same height as the existing utility pole, similar to the current lamp which we are replacing as well as the 2d streetmix view, both pasted below

streetmix
![image](https://user-images.githubusercontent.com/470477/147809106-b890c877-fa5a-413f-9f5a-7a20c890a815.png)

3dstreet
![image](https://user-images.githubusercontent.com/470477/147809112-e5ee3eac-4e7a-4774-a952-08271aa5b590.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/147813215-4831263c-b0b6-4e35-92b5-1b03c58512d3.png)
fixed the scale of street light

**Comment by kfarr** [comment]
Ok I think that's good for now, thanks! This is ready for implementation

**Comment by kfarr** [comment]
Ok these have been merged in 3dstreet-assets repo https://github.com/3DStreet/3dstreet-assets/pull/23, re

**Comment by srothst1** [comment]
@kfarr is this simply adding a new model to 3dstreet? I'm assuming it is the same process as in https://github.com/3DStreet/3dstreet/pull/118

**Comment by kfarr** [comment]
Yes very similar, the only differences will be:
- this is a repeating (cloned) street prop
- the rainbow / pride variant places a plane with the rainbow png manually here, the position values may need to be updated with the new models: https://github.com/3DStreet/3dstreet/blob/main/src/aframe-streetmix-parsers.js#L679

**Comment by kfarr** [comment]
Done via #129!
