### ISSUE TITLE
Migrate loose objects into "street-props" set

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#15]
The objects, located in https://github.com/3DStreet/3dstreet/tree/main/assets/objects can we converted to the new Blender workflow and combined into the "street-props" set:
palmtree,bikerack,bikeshare,lamp-post-traditional,seawall,track,parkbench,tree

**Comment by gnansai** [comment]
Yes, I will start working on these models.

**Comment by gnansai** [comment]
I could not find the parkbench and tree from https://github.com/3DStreet/3dstreet/tree/main/assets/objects

**Comment by kfarr** [comment]
They are in that directory but the filenames are not clear. Here they are:

Tree:
- SM_Env_Tree_03.bin
- SM_Env_Tree_03.gltf

Park Bench:
- SM_Prop_ParkBench_02.bin
- SM_Prop_ParkBench_02.gltf

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/street-props/gltf-exports
I uploaded to street-props
bike_rack
bike_share
lamp_post_traditional
palmtree
park_bench
sea_wall
track
tree-01

**Comment by kfarr** [comment]
It looks like this is ready for implementation, @srothst1 do you want to pick this up?

**Comment by srothst1** [comment]
@kfarr it seems like we simply need to update the file location and asset name in `assets.js`. Is that correct?

**Comment by srothst1** [comment]
So for instance in `assets.js`,
`<a-asset-item id="bikerackmodel" src="${assetUrl}assets/objects/bikerack.glb"></a-asset-item>`
gets deleted and we add 
`<a-mixin id="bike_rack" gltf-part-plus="src: #streetProps; part: bike_rack"></a-mixin>`

**Comment by kfarr** [comment]
Yes that's right!

**Comment by srothst1** [comment]
@kfarr okay, amazing!

**Comment by srothst1** [comment]
bike_rack -> done
bike_share
lamp_post_traditional
palmtree
park_bench
sea_wall
track
tree-01

**Comment by kfarr** [comment]
completed via PR 130!
