### ISSUE TITLE
Export individual glb files for each vehicle in `vehicles.glb`

### ISSUE THREAD

**Issue by srothst1** [3DStreet/3dstreet-assets#16]
Export individual glb files for each vehicle in vehicles.glb

cc https://github.com/3DStreet/3dstreet/issues/34

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/vehicles/individual-glb-files
exported the individual glb files

**Comment by kfarr** [comment]
confirmed and merged here: https://github.com/3DStreet/3dstreet-assets/tree/main/sets/vehicles/individual-glb-files

marking as closed
