### ISSUE TITLE
migrate suburban buildings to comply with 3d st model pipeline

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#18]
- migrate suburban buildings to comply with new model pipeline
- hopefully this fixes issue with invalid material

**Comment by kfarr** [comment]
the existing buildings are here:
https://github.com/3DStreet/3dstreet/blob/main/assets/objects/suburbia/suburbia-fixwindowuvs-only3-draco.glb

These should be brought into the same blender > gltf workflow as all other objects. Hopefully this will also fix an issue below

***
There is an issue that on some devices, some parts of the houses display inconsistently. I think it is something wrong with material on the trim of the house.  This results in a different color for the trim depending on device used.

mobile safari
![image](https://user-images.githubusercontent.com/470477/147779229-592fdb24-6760-419d-8a3b-282cf167390b.png)

desktop chrome
![image](https://user-images.githubusercontent.com/470477/147779272-fb75e12d-690d-4ae0-9c7f-17297232bf08.png)

**Comment by gnansai** [comment]
this suburban house contains a textured wall and roof. Shall I add that in our Texture atlas or make it flat color?
![image](https://user-images.githubusercontent.com/25223402/147800032-d5a4c8c7-c7d4-4d9d-b287-9ec61ba253cd.png)

**Comment by kfarr** [comment]
I think they are important to retain those two textures. Should this be a custom atlas just for this suburban house set so that we can keep this at 1 material? (Also no glass material for this version, they can be blue or black or another color, not sure what would be best.)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/147800945-ebce57a7-2b01-47b1-990a-9acf4b73ffd6.png)
we have empty space in our existing atlas , Shall I add those two texture here? or Shall we keep it as separate texture and Material?

**Comment by gnansai** [comment]
I have uploaded the houses here
https://github.com/gnansai/3dstreet-assets/tree/main/sets/suburban-houses/gltf-exports

**Comment by gnansai** [comment]
I have added new material for suburban-house here 
https://github.com/gnansai/3dstreet-assets/blob/main/materials/atlas_colors/altas-colors_2.blend

**Comment by kfarr** [comment]
Great progress, thanks!

Regarding file location for suburban house material: At the moment this texture is specific to this model, not shared with others. So it should probably be in model dir. From [Material Standards in readme](https://github.com/3dstreet/3dstreet-assets#material-standards):
> Textures specific to the model should go in the model’s textures folder. Atlas textures when appropriate (signage and graphics, non-repeating textures)

For the file name for suburban house material: instead of "altas-colors_2" could be "atlas-colors-suburban-houses" for example?

**Comment by gnansai** [comment]
I fixed the directories and material names

**Comment by kfarr** [comment]
A few minor updates:

on suburban house 1 - the windows should be a solid color, not a texture.
![image](https://user-images.githubusercontent.com/470477/147807909-ca96c8ba-a39b-42fb-96ea-c592093ae37d.png)

same on suburban house 2
![image](https://user-images.githubusercontent.com/470477/147808129-59819386-91fb-48ef-a209-37fc74d63ccf.png)

also these ones have a weird red tinge, maybe it is uv coordinate in between 2 colors, anyway it should just be the solid window color
![image](https://user-images.githubusercontent.com/470477/147808171-fdec7d54-f95f-4cf4-9e67-40e40ed83ee9.png)

suburban house 3 looks good
***
Another option is to start over from the original files from synty town pack which we also have licensed and you should have access to. Although I think the changes above are pretty quick and faster than starting over
![image](https://user-images.githubusercontent.com/470477/147807916-9890e1e2-16b6-4bab-82cb-3ed51cae5581.png)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/147813758-b4512a82-9395-412b-866b-b2f5e96e9a76.png)
I fixed the windows, Do let me know if you need any fixes.

**Comment by kfarr** [comment]
Ok this looks good! I will do a PR to bring these changes in, and then we can add this to the list of items to implement in the app

**Comment by kfarr** [comment]
Merged into assets, ready for implementation https://github.com/3DStreet/3dstreet-assets/pull/23

**Comment by srothst1** [comment]
@kfarr what else should be taken care of here?

**Comment by kfarr** [comment]
- This model should be updated with the new version from gnanasai https://github.com/3DStreet/3dstreet/tree/main/assets/objects/suburbia
- Then update assets.js here and the individual mixins elsewhere in the file https://github.com/3DStreet/3dstreet/blob/main/src/assets.js#L64
- Ideally that "just works" but you might also have to update logic in the building placement https://github.com/3DStreet/3dstreet/blob/main/src/aframe-streetmix-parsers.js#L739

**Comment by srothst1** [comment]
@kfarr sounds good - I will take a look at this later today.

**Comment by kfarr** [comment]
done!
