### ISSUE TITLE
new object: magic carpet

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#19]

**Comment by gnansai** [comment]
Please share any reference images for this

**Comment by kfarr** [comment]
Here is an example from streetmix:
![image](https://user-images.githubusercontent.com/470477/147809421-2b907855-ebeb-405a-ac48-a3a9c30afe5d.png)

it appears to be bright red carpet on top, darker red on bottom, yellow tufts in each corner, slight wave

Here is an example of animated carpet, too fancy for now but to give you an idea of the general style:
https://sketchfab.com/3d-models/carpet-of-flying-9f6b6cfeff564def8e3a72aa5f266562

**Comment by gnansai** [comment]
I added magic-carpet with character here

https://github.com/gnansai/3dstreet-assets/tree/main/sets/magic-carpet/gltf-exports
![image](https://user-images.githubusercontent.com/25223402/148491025-b35a57e8-9f43-4dbe-86e0-a82ac69fc2a7.png)

**Comment by srothst1** [comment]
@kfarr am I good to go for the 3DStreet implementation?

**Comment by kfarr** [comment]
Yes! I also just [merged his changes to the repo](https://github.com/3DStreet/3dstreet-assets/commit/0fccb1e8c2826ec1edb4111a73706c2c98b7497d) but it's the same as you're using from gnanasai's fork already

**Comment by srothst1** [comment]
@kfarr I didn't even notice that I was on @gnansai's fork. Glad it's okay regardless.

**Comment by kfarr** [comment]
deployed! looks beautiful! 
![image](https://user-images.githubusercontent.com/470477/148972567-a695faa1-f388-4409-92fa-7689d4c6b8df.png)
