### ISSUE TITLE
Simplified model for transit shelter

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#22]

**Comment by gnansai** [comment]
Please share reference images for this

**Comment by kfarr** [comment]
Here is visual from streetmix
![image](https://user-images.githubusercontent.com/470477/147815322-4878f740-9233-40c1-8263-b35f65b901d5.png)

It looks like there might be a model we could use from the city pack we licensed from synty
![image](https://user-images.githubusercontent.com/470477/147815596-a506eed2-877a-435e-a221-0839c4b0c340.png)

**Comment by kfarr** [comment]
Sharing progress from discord:
![image](https://user-images.githubusercontent.com/470477/148127993-58df46ae-5e91-44c5-9225-097b85b79654.png)

![image](https://user-images.githubusercontent.com/470477/148128004-58ec98f1-ae67-446e-a24c-723a0156f37a.png)

![image](https://user-images.githubusercontent.com/470477/148128012-db6c90f9-645c-482b-97bc-1056757ea033.png)

reflective
![image](https://user-images.githubusercontent.com/470477/148128029-d9578110-d242-428b-8dbe-997080e9f082.png)

![image](https://user-images.githubusercontent.com/470477/148128041-f2f2e258-d232-43f6-aca3-20a3a7f7549c.png)

**Comment by kfarr** [comment]
Yes these look good @gnansai  ! I think we should store the 1 material version as part of the street-props set. The 2 material version can be a standalone like the vehicles

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/148152963-2ef36dc0-7450-4522-ada0-2598b066b222.png)
I changed the Bench,

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/148153049-98f7ce89-ee45-4563-ab90-7671e1e8514f.png)
I changed the bench to metal, @kfarr @srothst1  Let me know your suggestions on this.

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/tree/main/sets/street-props/gltf-exports
https://github.com/gnansai/3dstreet-assets/tree/main/sets/transit-shelter-2/gltf-exports
Added transit shealter-1 in street-props & -2 separately

**Comment by srothst1** [comment]
@kfarr am I good to go for the 3DStreet implementation?

**Comment by kfarr** [comment]
merged!
