### ISSUE TITLE
Change new flyer bus material from "unlit" to same as other objects

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#28]
Issue: The material used on the bus appears to be "unlit" or otherwise does not respect the scene's lighting conditions
Instead: update the material to be the same as other 3dstreet objects so that when appearing in dark scenes the material appropriately renders

![image](https://user-images.githubusercontent.com/470477/174689820-121613d9-377f-4ac3-bd22-91e982741111.png)

Here is the highest quality original file that we have for the bus:
https://github.com/3DStreet/3dstreet/blob/main/assets/objects/bus/XD40.glb

**Comment by JLansey** [comment]
Wow this looks sooo good!!!!

**Comment by gnansai** [comment]
I uploaded the flyer-bus with normal material as other 3dstreet models.
I am using same textures as the original flyer-bus.
https://github.com/gnansai/3dstreet-assets/tree/main/sets/flyer-bus/gltf-eports

![image](https://user-images.githubusercontent.com/25223402/175817769-90789744-e7be-4366-9423-f803491bec3c.png)

**Comment by kfarr** [comment]
looking good in https://github.com/3DStreet/3dstreet/pull/183
