### ISSUE TITLE
animate wheel rotation on vehicles

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#30]
Start with 1 vehicle object (sedan) add animation to all 4 tires turning forwards at a speed of:
- There should be one full wheel rotation every 2.60869 seconds. (This rate is that of a car that is navigating at 1 m/s. https://github.com/3DStreet/3dstreet/pull/182#issuecomment-1165936717)

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/180782539-06570679-b99a-4808-93db-9291a5471904.png)
![image](https://user-images.githubusercontent.com/25223402/180782604-dd113c9e-ddea-4b17-93b1-fac1abc8b0b4.png)

**Comment by gnansai** [comment]
https://github.com/gnansai/3dstreet-assets/blob/main/sets/vehicles-animation/gltf-exports/sedan-wheel-rotation.glb

**Comment by gnansai** [comment]
![image](https://user-images.githubusercontent.com/25223402/180784070-c6a75de1-4896-4c14-8698-be3fb156bd45.png)
I have used the Rig to Animate the wheels.

**Comment by gnansai** [comment]
https://wealthy-rural-larch.glitch.me
I am experimenting with A-Frame Component.

Here is the link to the source
https://glitch.com/edit/#!/wealthy-rural-larch

**Comment by gnansai** [comment]
r = number of rotations;
d = distance travelled by Vehicle;
c =  circumference of the wheel;

r = d / c ;

I followed this for wheel rotation

https://user-images.githubusercontent.com/25223402/181603279-52f4c9e6-c02b-4f8e-9130-94a60772fb5b.mp4

**Comment by kfarr** [comment]
This is great! I'm marking this ticket as done, I made 2 others to represent the next steps:
- formalize the wheel component: https://github.com/3DStreet/3dstreet/issues/190
- convert the rest of the assets: https://github.com/3DStreet/3dstreet-assets/issues/35
