### ISSUE TITLE
Create green ray gun model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#33]
create an old sci fi style green "ray gun"

a low poly, green-ish version of this:
![Image](https://user-images.githubusercontent.com/470477/180577463-38daf6d3-dd07-47e7-b5b7-9d7edac744bd.png)

**Comment by JLansey** [comment]
@gnansai here is the link to the high res 3d file 

https://sketchfab.com/3d-models/dope-raygun-cc39a093ccc04d1690aeee82459314f8

**Comment by gnansai** [comment]
![unknown](https://user-images.githubusercontent.com/25223402/181434484-6f05143f-874e-4b1e-a187-d792eacebf85.png)
Here is an update on Green Ray Gun.
Please check it and let me know your suggestions.

**Comment by gnansai** [comment]
![unknown](https://user-images.githubusercontent.com/25223402/181876984-d80a6e9d-18d0-4257-bb51-7bb1cd67cf4a.png)
![unknown](https://user-images.githubusercontent.com/25223402/181876985-c1958b75-f759-4dd0-9118-b021299f1873.png)

**Comment by JLansey** [comment]
I really love the colors again. Nice job with the light blue.
Regarding the shape - can we increase the diameter of the three smaller disks as well, especially the largest one. And also sink them deeper into the dish.
The goal is to make the gun look a little more balanced and slightly silly.

**Comment by gnansai** [comment]
Here is an Update.
![image](https://user-images.githubusercontent.com/25223402/182075595-daf82adc-687c-4cbd-b708-c6cc942d5356.png)
![image](https://user-images.githubusercontent.com/25223402/182075613-1ebba873-ce1f-470d-89d4-ef718c4b133f.png)

**Comment by kfarr** [comment]
This looks good to me, I'd suggest marking as done and I will merge in the 3dstreet-assets repo

**Comment by JLansey** [comment]
Looks great!!! Love it. Sorry i hadn't seen the update
