### ISSUE TITLE
New object: bench orientation center

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-assets#8]
- There is an existing bench model
- It should be modified to be a bench with no back (just a flat bench to sit on)
- it should also be converted into a model that is compliant with this new blender workflow to have a shared atlas
- In addition, the other existing bench model should be converted to a model with this new workflow
- they should be added to a new set "street-props"

 (For gnanasai to modify existing bench to not have a back, just a flat surface)

**Comment by gnansai** [comment]
Could you share me the link or image of existing bench model?

**Comment by kfarr** [comment]
in this directory https://github.com/3DStreet/3dstreet/tree/main/assets/objects

there are 3 files:
- https://github.com/3DStreet/3dstreet/blob/main/assets/objects/PolygonCity_Texture.png
- https://github.com/3DStreet/3dstreet/blob/main/assets/objects/SM_Prop_ParkBench_02.bin
- https://github.com/3DStreet/3dstreet/blob/main/assets/objects/SM_Prop_ParkBench_02.gltf
